services:
  db:
    image: postgres:18.2-alpine
    ports:
      - "5434:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - "secrets.env"

volumes:
  pgdata:

